spring:
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anime_test01
    username: root
    password: root
#    type: com.alibaba.druid.pool.DruidDataSource

animeTest:
  num01: ${random.int}
  num02: ${random.int(10,20)}
  num03: ${random.uuid}
  num04: ${random.value}
  num05: ${random.long}