spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: root
  h2:
    console:
      path: /h2
      enabled: true

#    type: com.alibaba.druid.pool.DruidDataSource

animeTest:
  num01: ${random.int}
  num02: ${random.int(10,20)}
  num03: ${random.uuid}
  num04: ${random.value}
  num05: ${random.long}